const entries = {
    "Jan 12": {
        "day": "Monday",
        "dayNum": 12,
        "costMorning": 65.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:41:00 AM",
        "checkInMorning": 521,
        "changeRealTimeMorning": "8:57:00 AM",
        "changeTimeMorning": 537,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:30:00 AM",
        "checkOutMorning": 570,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "4:46:00 PM",
        "checkInEvening": 1006,
        "changeRealTimeEvening": "4:48:00 PM",
        "changeTimeEvening": 1008,
        "secondModeEvening": "metro",
        "checkOutRealTimeEvening": "5:04:00 PM",
        "checkOutEvening": 1024,
        "targetRealTimeEvening": "17:30",
        "targetTimeEvening": 1050
    },
    "Jan 13": {
        "day": "Tuesday",
        "dayNum": 13,
        "costMorning": 28,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:33:00 AM",
        "checkInMorning": 513,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "8:45:00 AM",
        "checkOutMorning": 525,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "4:52:00 PM",
        "checkInEvening": 1012,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "metro",
        "checkOutRealTimeEvening": "5:12:00 PM",
        "checkOutEvening": 1032,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Jan 14": {
        "day": "Wednesday",
        "dayNum": 14,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 15": {
        "day": "Thursday",
        "dayNum": 15,
        "costMorning": 37.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:35:00 AM",
        "checkInMorning": 515,
        "changeRealTimeMorning": "8:54:00 AM",
        "changeTimeMorning": 534,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:30:00 AM",
        "checkOutMorning": 570,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:18",
        "checkInEvening": 1038,
        "changeRealTimeEvening": "5:26:00 PM",
        "changeTimeEvening": 1046,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "5:30:00 PM",
        "checkOutEvening": 1050,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 16": {
        "day": "Friday",
        "dayNum": 16,
        "costMorning": 23.75,
        "modeMorning": "IC",
        "checkInRealTimeMorning": "9:04:00 AM",
        "checkInMorning": 544,
        "changeRealTimeMorning": "9:13:00 AM",
        "changeTimeMorning": 553,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:24:00 AM",
        "checkOutMorning": 564,
        "targetRealTimeMorning": "9:30",
        "targetTimeMorning": 570,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:30:00 PM",
        "checkInEvening": 1050,
        "changeRealTimeEvening": "5:41:00 PM",
        "changeTimeEvening": 1061,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "5:45:00 PM",
        "checkOutEvening": 1065,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 17": {
        "day": "Saturday",
        "dayNum": 17,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 18": {
        "day": "Sunday",
        "dayNum": 18,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 19": {
        "day": "Monday",
        "dayNum": 19,
        "costMorning": 23.8,
        "modeMorning": "train",
        "checkInRealTimeMorning": "11:43:00 AM",
        "checkInMorning": 703,
        "changeRealTimeMorning": "11:57:00 AM",
        "changeTimeMorning": 717,
        "secondModeMorning": "metro",
        "checkOutRealTime": "11:59:00 AM",
        "checkOutMorning": 719,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:42:00 PM",
        "checkInEvening": 1062,
        "changeRealTimeEvening": "5:54:00 PM",
        "changeTimeEvening": 1074,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "6:02:00 PM",
        "checkOutEvening": 1082,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 20": {
        "day": "Tuesday",
        "dayNum": 20,
        "costMorning": null,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:53:00 AM",
        "checkInMorning": 533,
        "changeRealTimeMorning": "9:01:00 AM",
        "changeTimeMorning": 541,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:11:00 AM",
        "checkOutMorning": 551,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "4:39:00 PM",
        "checkInEvening": 999,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "4:58:00 PM",
        "checkOutEvening": 1018,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Jan 21": {
        "day": "Wednesday",
        "dayNum": 21,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 22": {
        "day": "Thursday",
        "dayNum": 22,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:44:00 AM",
        "checkInMorning": 524,
        "changeRealTimeMorning": "8:52:00 AM",
        "changeTimeMorning": 532,
        "secondModeMorning": "metro",
        "checkOutRealTime": "8:58:00 AM",
        "checkOutMorning": 538,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:16:00 PM",
        "checkInEvening": 1036,
        "changeRealTimeEvening": "5:27:00 PM",
        "changeTimeEvening": 1047,
        "secondModeEvening": "train",
        "checkOutRealTimeEvening": "5:38:00 PM",
        "checkOutEvening": 1058,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 23": {
        "day": "Friday",
        "dayNum": 23,
        "costMorning": 23.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:53:00 AM",
        "checkInMorning": 533,
        "changeRealTimeMorning": "9:01:00 AM",
        "changeTimeMorning": 541,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:09:00 AM",
        "checkOutMorning": 549,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:27:00 PM",
        "checkInEvening": 1047,
        "changeRealTimeEvening": "5:35:00 PM",
        "changeTimeEvening": 1055,
        "secondModeEvening": "train",
        "checkOutRealTimeEvening": "5:47:00 PM",
        "checkOutEvening": 1067,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 24": {
        "day": "Saturday",
        "dayNum": 24,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 25": {
        "day": "Sunday",
        "dayNum": 25,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 26": {
        "day": "Monday",
        "dayNum": 26,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:58:00 AM",
        "checkInMorning": 538,
        "changeRealTimeMorning": "9:06:00 AM",
        "changeTimeMorning": 546,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:12:00 AM",
        "checkOutMorning": 552,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:50:00 PM",
        "checkInEvening": 1070,
        "changeRealTimeEvening": "5:57:00 PM",
        "changeTimeEvening": 1077,
        "secondModeEvening": "train",
        "checkOutRealTimeEvening": "6:09:00 PM",
        "checkOutEvening": 1089,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 27": {
        "day": "Tuesday",
        "dayNum": 27,
        "costMorning": 23.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:53:00 AM",
        "checkInMorning": 533,
        "changeRealTimeMorning": "9:01:00 AM",
        "changeTimeMorning": 541,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:08:00 AM",
        "checkOutMorning": 548,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "16:38",
        "checkInEvening": 998,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "16:55",
        "checkOutEvening": 1015,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Jan 28": {
        "day": "Wednesday",
        "dayNum": 28,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 29": {
        "day": "Thursday",
        "dayNum": 29,
        "costMorning": 45.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "9:12:00 AM",
        "checkInMorning": 552,
        "changeRealTimeMorning": "9:27:00 AM",
        "changeTimeMorning": 567,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:30:00 AM",
        "checkOutMorning": 570,
        "targetRealTimeMorning": "10:00",
        "targetTimeMorning": 600,
        "costEvening": 19,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "6:28:00 PM",
        "checkInEvening": 1108,
        "changeRealTimeEvening": "6:34:00 PM",
        "changeTimeEvening": 1114,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "6:47:00 PM",
        "checkOutEvening": 1127,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 30": {
        "day": "Friday",
        "dayNum": 30,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:49:00 AM",
        "checkInMorning": 529,
        "changeRealTimeMorning": "8:58:00 AM",
        "changeTimeMorning": 538,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:13:00 AM",
        "checkOutMorning": 553,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Jan 31": {
        "day": "Saturday",
        "dayNum": 31,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 1": {
        "day": "Sunday",
        "dayNum": 1,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 2": {
        "day": "Monday",
        "dayNum": 2,
        "costMorning": 23.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:46:00 AM",
        "checkInMorning": 526,
        "changeRealTimeMorning": "8:55:00 AM",
        "changeTimeMorning": 535,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:04:00 AM",
        "checkOutMorning": 544,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "5:39:00 PM",
        "checkInEvening": 1059,
        "changeRealTimeEvening": "5:51:00 PM",
        "changeTimeEvening": 1071,
        "secondModeEvening": "bus",
        "checkOutRealTimeEvening": "5:57:00 PM",
        "checkOutEvening": 1077,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 3": {
        "day": "Tuesday",
        "dayNum": 3,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:58",
        "checkInMorning": 538,
        "changeRealTimeMorning": "9:02",
        "changeTimeMorning": 542,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:07",
        "checkOutMorning": 547,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "16:38",
        "checkInEvening": 998,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "16:54",
        "checkOutEvening": 1014,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Feb 4": {
        "day": "Wednesday",
        "dayNum": 4,
        "costMorning": 17.6,
        "modeMorning": "IC",
        "checkInRealTimeMorning": "11:57",
        "checkInMorning": 717,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "12:22",
        "checkOutMorning": 742,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 5": {
        "day": "Thursday",
        "dayNum": 5,
        "costMorning": 29.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:33",
        "checkInMorning": 513,
        "changeRealTimeMorning": "8:52",
        "changeTimeMorning": 532,
        "secondModeMorning": "metro",
        "checkOutRealTime": "8:58",
        "checkOutMorning": 538,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:28",
        "checkInEvening": 1048,
        "changeRealTimeEvening": "17:38",
        "changeTimeEvening": 1058,
        "secondModeEvening": "train",
        "checkOutRealTimeEvening": "17:45",
        "checkOutEvening": 1065,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 6": {
        "day": "Friday",
        "dayNum": 6,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "9:02",
        "checkInMorning": 542,
        "changeRealTimeMorning": "9:22",
        "changeTimeMorning": 562,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:23",
        "checkOutMorning": 563,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:16",
        "checkInEvening": 1036,
        "changeRealTimeEvening": "17:26",
        "changeTimeEvening": 1046,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "17:33",
        "checkOutEvening": 1053,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 7": {
        "day": "Saturday",
        "dayNum": 7,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 8": {
        "day": "Sunday",
        "dayNum": 8,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 9": {
        "day": "Monday",
        "dayNum": 9,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 10": {
        "day": "Tuesday",
        "dayNum": 10,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:36",
        "checkInMorning": 516,
        "changeRealTimeMorning": "8:54",
        "changeTimeMorning": 534,
        "secondModeMorning": "metro",
        "checkOutRealTime": "8:56",
        "checkOutMorning": 536,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "16:40",
        "checkInEvening": 1000,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "16:56",
        "checkOutEvening": 1016,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Feb 11": {
        "day": "Wednesday",
        "dayNum": 11,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 12": {
        "day": "Thursday",
        "dayNum": 12,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:42",
        "checkInMorning": 522,
        "changeRealTimeMorning": "9:06",
        "changeTimeMorning": 546,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:10",
        "checkOutMorning": 550,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 19,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "19:11",
        "checkInEvening": 1151,
        "changeRealTimeEvening": "19:20",
        "changeTimeEvening": 1160,
        "secondModeEvening": "bus",
        "checkOutRealTimeEvening": "19:34",
        "checkOutEvening": 1174,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 13": {
        "day": "Friday",
        "dayNum": 13,
        "costMorning": 23.75,
        "modeMorning": "regional",
        "checkInRealTimeMorning": "8:44",
        "checkInMorning": 524,
        "changeRealTimeMorning": "8:55",
        "changeTimeMorning": 535,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:03",
        "checkOutMorning": 543,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:26",
        "checkInEvening": 1046,
        "changeRealTimeEvening": "17:37",
        "changeTimeEvening": 1057,
        "secondModeEvening": "metro",
        "checkOutRealTimeEvening": "17:43",
        "checkOutEvening": 1063,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 14": {
        "day": "Saturday",
        "dayNum": 14,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 15": {
        "day": "Sunday",
        "dayNum": 15,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 16": {
        "day": "Monday",
        "dayNum": 16,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 17": {
        "day": "Tuesday",
        "dayNum": 17,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 18": {
        "day": "Wednesday",
        "dayNum": 18,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 19": {
        "day": "Thursday",
        "dayNum": 19,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 20": {
        "day": "Friday",
        "dayNum": 20,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 21": {
        "day": "Saturday",
        "dayNum": 21,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 22": {
        "day": "Sunday",
        "dayNum": 22,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": null,
        "modeEvening": "",
        "checkInRealTimeEvening": "",
        "checkInEvening": null,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "",
        "checkOutEvening": null,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 23": {
        "day": "Monday",
        "dayNum": 23,
        "costMorning": null,
        "modeMorning": "",
        "checkInRealTimeMorning": "",
        "checkInMorning": null,
        "changeRealTimeMorning": "",
        "changeTimeMorning": null,
        "secondModeMorning": "",
        "checkOutRealTime": "",
        "checkOutMorning": null,
        "targetRealTimeMorning": "",
        "targetTimeMorning": null,
        "costEvening": 30.4,
        "modeEvening": "regional",
        "checkInRealTimeEvening": "19:00",
        "checkInEvening": 1140,
        "changeRealTimeEvening": "19:28",
        "changeTimeEvening": 1168,
        "secondModeEvening": "train",
        "checkOutRealTimeEvening": "19:41",
        "checkOutEvening": 1181,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    },
    "Feb 24": {
        "day": "Tuesday",
        "dayNum": 24,
        "costMorning": 29.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:43",
        "checkInMorning": 523,
        "changeRealTimeMorning": "8:58",
        "changeTimeMorning": 538,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:00",
        "checkOutMorning": 540,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "16:43",
        "checkInEvening": 1003,
        "changeRealTimeEvening": "",
        "changeTimeEvening": null,
        "secondModeEvening": "",
        "checkOutRealTimeEvening": "16:57",
        "checkOutEvening": 1017,
        "targetRealTimeEvening": "17:00",
        "targetTimeEvening": 1020
    },
    "Feb 25": {
        "day": "Wednesday",
        "dayNum": 25,
        "costMorning": 23.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "14:52",
        "checkInMorning": 892,
        "changeRealTimeMorning": "15:02",
        "changeTimeMorning": 902,
        "secondModeMorning": "metro",
        "checkOutRealTime": "15:08",
        "checkOutMorning": 908,
        "targetRealTimeMorning": "15:00",
        "targetTimeMorning": 900,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:48",
        "checkInEvening": 1068,
        "changeRealTimeEvening": "17:49",
        "changeTimeEvening": 1069,
        "secondModeEvening": "metro",
        "checkOutRealTimeEvening": "17:57",
        "checkOutEvening": 1077,
        "targetRealTimeEvening": "18:00",
        "targetTimeEvening": 1080
    },
    "Feb 26": {
        "day": "Thursday",
        "dayNum": 26,
        "costMorning": 23.75,
        "modeMorning": "train",
        "checkInRealTimeMorning": "8:55",
        "checkInMorning": 535,
        "changeRealTimeMorning": "9:01",
        "changeTimeMorning": 541,
        "secondModeMorning": "metro",
        "checkOutRealTime": "9:07",
        "checkOutMorning": 547,
        "targetRealTimeMorning": "9:00",
        "targetTimeMorning": 540,
        "costEvening": 23.75,
        "modeEvening": "metro",
        "checkInRealTimeEvening": "17:57",
        "checkInEvening": 1077,
        "changeRealTimeEvening": "18:08",
        "changeTimeEvening": 1088,
        "secondModeEvening": "regional",
        "checkOutRealTimeEvening": "18:16",
        "checkOutEvening": 1096,
        "targetRealTimeEvening": "",
        "targetTimeEvening": null
    }
}